# Generated by Django 4.0.4 on 2022-04-18 11:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('neighbourhood', '0002_profile_username_person'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Post',
        ),
    ]
