# Generated by Django 4.0.4 on 2022-04-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0006_post_neighbourhood_location_post_neighbourhood_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='neighbourhood_location',
            field=models.CharField(default='Enter your location', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='neighbourhood_name',
            field=models.CharField(default='Enter nickname', max_length=100),
        ),
    ]
